больше данных в бд
Farcim/book-market pull request #10
Opened 2022-07-02 17:10 UTC by Farcim

2022-07-02 20:50 UTC, Frankynz requested changes

2022-07-02 20:50 UTC, Frankynz commented on src/main/resources/db/migration/V2__inser_defaul_values.sql
> +       (6, 'A.S.Pushkin1'),
Все должно быть на одном языке.
Не должно быть авторов с постфиксами123455 и тд

2022-07-02 20:50 UTC, Frankynz commented on src/main/resources/db/migration/V2__inser_defaul_values.sql
> +       (2, 'Роковые яйца', 242),
Сделай минимум 15 книг

2022-07-02 20:50 UTC, Frankynz commented on src/main/resources/db/migration/V2__inser_defaul_values.sql
> +       (2, 2),
подпиши связи

2022-07-03 09:15 UTC, Farcim commented
Навел порядок, что бы название столбца соответствовало его конструктору

2022-07-03 10:03 UTC, Frankynz approved these changes

2022-07-03 10:03 UTC, merged