Feature/default openapi
Farcim/book-market pull request #11
Opened 2022-07-05 09:10 UTC by Farcim

2022-07-05 15:45 UTC, Frankynz requested changes

2022-07-05 15:45 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/dto/AuthorDTO.java
> +    @Schema(type = "string", example = " ")
Зачем тупо брать и копипастить?
подумать может быть надо ?
если у тебя айдишник лонг, то схуяли он в сваггере должен быть показан как стринг ?

2022-07-05 15:45 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/dto/AuthorDTO.java
> +    @Schema(type = "string", example = " ")
Примеры делай живые. 
То есть какие то реальные данные

2022-07-05 15:45 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/dto/BookDTO.java
>  @Builder
тоже самое

2022-07-05 15:45 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/dto/BookDTOSave.java
>  public class BookDTOSave {
тоже самое

2022-07-05 15:45 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/dto/BookDTOSave.java
> +    @GeneratedValue(strategy = GenerationType.AUTO)
зачем тебе тут генерить ?
удали

2022-07-07 09:33 UTC, Frankynz requested changes

2022-07-07 09:33 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/controller/AuthorController.java
> +    Page<AuthorDTO> getByPage(@PageableDefault() Pageable pageable);
Зачем дефолтные убрал?

2022-07-07 12:32 UTC, Farcim commented on src/main/java/ru/example/bookmarket/controller/AuthorController.java
> +    Page<AuthorDTO> getByPage(@PageableDefault() Pageable pageable);
похуй

2022-07-07 12:43 UTC, Farcim commented on src/main/java/ru/example/bookmarket/controller/AuthorController.java
> +    Page<AuthorDTO> getByPage(@PageableDefault() Pageable pageable);
они все равно не работают

2022-07-07 13:18 UTC, Frankynz approved these changes

2022-07-07 13:18 UTC, merged