картинки
Farcim/book-market pull request #16
Opened 2022-07-09 13:57 UTC by Farcim

2022-07-10 07:44 UTC, Frankynz requested changes

2022-07-10 07:44 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/controller/ImageController.java
> +    @GetMapping("/{id}")
а описание остальных ?

2022-07-10 07:44 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/controller/Impl/ImageControllerImpl.java
> +    public Image findById(@PathVariable Long id) {
нужен эндпоинт по которому ты сможешь получать все картинки для какой то книги.

2022-07-10 07:44 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/dto/BookDTO.java
> +    private List<Image> images;
не надо добавлять в бук дто книги. 
Слишком тяжело будет

2022-07-10 07:44 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/model/Book.java
> +    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
каскад тайп должен быть другой. Чтобы картинки все не удалились.

2022-07-10 07:44 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/repository/ImageRepository.java
> +public interface ImageRepository extends JpaRepository<Image,Long> {
код стайл поправь 
+ аннотацию забыл

2022-07-10 07:44 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/service/BookService.java
> +import ru.example.bookmarket.repository.ImageRepository;
импорты лишние

2022-07-10 07:44 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/service/ImageService.java
> +    ImageRepository imageRepository;
где модификатооры?
у тебя этот класс даже не сработает

2022-07-10 07:44 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/service/ImageService.java
> +            throw new EntityNotFoundException("Image with id '%d' not exist");
ты не передал айдишник

2022-07-10 07:44 UTC, Frankynz commented on src/main/resources/db/migration/V1__Init_DB.sql
> +create table book_images
не надо менять старые файлы 
надо добавлять новые

2022-07-11 06:25 UTC, Frankynz requested changes

2022-07-11 06:25 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/model/Book.java
> +    @ManyToMany(cascade = CascadeType.DETACH, fetch = FetchType.LAZY)
Зачем делать дефолтное значение ?

2022-07-11 06:25 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/repository/ImageRepository.java
> +public interface ImageRepository extends JpaRepository<Image,Long> {
код стайл не поправил

2022-07-11 06:25 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/service/BookService.java
> +
лучше убери эту строчку

2022-07-11 06:25 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/service/ImageService.java
> +                .orElseThrow(EntityNotFoundException::new);
Ты не передаешь текст ошибки

2022-07-11 06:25 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/util/Converter.java
> +    @SneakyThrows
очень меня напрягает это

2022-07-11 06:25 UTC, Frankynz commented on src/main/resources/application.yml
> +#      create: создает схему, уничтожая предыдущие данные.
к чему коменты ?

2022-07-11 06:25 UTC, Frankynz commented on src/main/resources/db/migration/V1__Init_DB.sql
> +
убери строчку

2022-07-11 06:25 UTC, Frankynz commented on src/main/resources/db/migration/V3__Init_image_table.sql
> +create table image
добавь дефолтную картинку

2022-07-11 08:55 UTC, Farcim commented on src/main/java/ru/example/bookmarket/repository/ImageRepository.java
> +public interface ImageRepository extends JpaRepository<Image,Long> {
нажимаю поправить нихуя не меняется

2022-07-11 16:35 UTC, Frankynz requested changes

2022-07-11 16:35 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/controller/ImageController.java
> +    List<Image> save(@RequestBody() List<MultipartFile> files) throws IOException;
не делай так. Оберни в трай кетч и не надо будет менять сигнатуру метода

2022-07-11 16:35 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/service/ImageService.java
> +        } else throw new ImageNotFoundException(id);
а где тело else

2022-07-11 16:35 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/util/Converter.java
> +            e.printStackTrace();
надо писать в логгер и не надо печатать стек трейс
за тебя это делает логгер
почитай про аннотацию ломбока @Sl4j

2022-07-11 16:35 UTC, Frankynz commented on src/main/resources/db/migration/V4__insert_image.sql
> +values ('files', 'image/jpeg', 507538, 43302)
уверен что байты выглядят так:?

2022-07-13 09:37 UTC, Frankynz requested changes

2022-07-13 09:37 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/util/Converter.java
> +        return null;
тут будет прикол в том, что ты будешь в базу пытаться сохранить налл. Это не есть хорошо. Лучше в блоке кетч, выбрасывай свое исключение.

2022-07-13 09:37 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/util/Converter.java
> +            log.info("Something went wrong, please try again later.");
ты забыл тут еще добавить эксепшн

2022-10-11 19:08 UTC, closed without merging