забыл один сэт во множественное число перевести ну и база данных
Farcim/book-market pull request #6
Opened 2022-06-13 14:26 UTC by Farcim

2022-06-17 15:41 UTC, Farcim commented
короче я не ебу как мне новую ветку открыть что бы старые сохранения подтянулись так что ебашу 2 комита на 1 ветке не бомби сам виноват не мергишь и  не чекаешь

2022-06-17 19:57 UTC, Frankynz requested changes

2022-06-17 19:57 UTC, Frankynz commented on docker/docker-compose.yml
> -version: "3.9"
нахуя удалил?

2022-06-17 19:57 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/dto/BookDTO.java
> +    private Set<AuthorDTO> authors;
зачем смешивать два пра:?

2022-06-17 19:57 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/dto/GenreDTO.java
> +public class GenreDTO {
зачем тебе дто для жанра если есть енам

2022-06-17 19:57 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/util/Converter.java
> +    public static GenreDTO genreToDTO(Genre genre) {
я тебя просил сделать через енам а не дто

2022-06-18 09:30 UTC, Farcim commented on docker/docker-compose.yml
> -version: "3.9"
ты через докер запускаешь что ли

2022-06-18 09:31 UTC, Farcim commented on src/main/java/ru/example/bookmarket/dto/BookDTO.java
> +    private Set<AuthorDTO> authors;
пра?

2022-06-18 09:32 UTC, Frankynz commented on docker/docker-compose.yml
> -version: "3.9"
ну да, ради тебя качать постгрес чтоли

2022-06-18 09:32 UTC, Farcim commented on src/main/java/ru/example/bookmarket/dto/GenreDTO.java
> +public class GenreDTO {
ты мне сказал сделать

2022-06-18 09:32 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/dto/BookDTO.java
> +    private Set<AuthorDTO> authors;
пул реквеста даун

2022-06-18 09:33 UTC, Frankynz commented on src/main/java/ru/example/bookmarket/dto/GenreDTO.java
> +public class GenreDTO {
я тебе сказал сделать через енам

2022-06-29 14:47 UTC, closed without merging